# Main Terraform configuration for devops-cli
# Generated by Rig CLI
# Project: aibrandedbooth
# Region: us-central1

terraform {
  required_version = ">= 1.0"
  
  backend "gcs" {
    bucket = var.terraform_state_bucket
    prefix = "terraform/state"
  }
}

provider "gcp" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}

# Local values for common tags and naming
locals {
  common_tags = {
    Environment   = var.environment
    Project       = var.project_name
    ManagedBy     = "terraform"
    GeneratedBy   = "rig-cli"
    CreatedDate   = formatdate("YYYY-MM-DD", timestamp())
  }
  
  name_prefix = "${var.project_name}-${var.environment}"
}

# Data sources
data "google_client_config" "default" {}

data "google_project" "project" {
  project_id = var.project_id
}

# Module calls will be added here based on your infrastructure

# Storage buckets module
module "storage" {
  source = "./modules/storage"
  
  project_id   = var.project_id
  region       = var.region
  name_prefix  = local.name_prefix
  common_tags  = local.common_tags
}
