# Variable definitions
# Generated by Rig CLI

variable "project_id" {
  description = "The GCP project ID"
  type        = string
  default     = "aibrandedbooth"
}

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "devops-cli"
}

variable "region" {
  description = "The GCP region"
  type        = string
  default     = "us-central1"
}

variable "zone" {
  description = "The GCP zone"
  type        = string
  default     = "us-central1-a"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
  
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be dev, staging, or prod."
  }
}

variable "terraform_state_bucket" {
  description = "GCS bucket for Terraform state"
  type        = string
}

