# CIS Kubernetes Benchmark Controls
apiVersion: v1
kind: ConfigMap
metadata:
  name: cis-benchmark-config
  namespace: compliance
data:
  cis-controls.yaml: |
    controls:
      # Control 5.1.1: Ensure that the cluster-admin role is only used where required
      - id: "5.1.1"
        description: "Minimize access to cluster-admin role"
        check: |
          kubectl get clusterrolebindings -o json | jq -r '.items[] | select(.roleRef.name=="cluster-admin") | .subjects[]?'
        remediation: |
          Remove unnecessary cluster-admin bindings and use more restrictive roles
      
      # Control 5.1.3: Minimize wildcard use in Roles and ClusterRoles
      - id: "5.1.3"
        description: "Minimize wildcard use in RBAC"
        check: |
          kubectl get roles,clusterroles -A -o json | jq -r '.items[] | select(.rules[]?.resources[]? == "*" or .rules[]?.verbs[]? == "*")'
        remediation: |
          Replace wildcard permissions with specific resource and verb permissions
      
      # Control 5.2.2: Minimize the admission of containers wishing to share the host process ID namespace
      - id: "5.2.2"
        description: "Restrict hostPID usage"
        check: |
          kubectl get pods -A -o json | jq -r '.items[] | select(.spec.hostPID == true)'
        remediation: |
          Remove hostPID: true from pod specifications unless absolutely necessary
      
      # Control 5.3.2: Ensure that all Namespaces have Network Policies defined
      - id: "5.3.2"
        description: "Ensure Network Policies are defined"
        check: |
          kubectl get networkpolicies -A --no-headers | wc -l
        remediation: |
          Create NetworkPolicy resources for all namespaces to restrict traffic
      
      # Control 5.7.3: Apply Security Context to Your Pods and Containers
      - id: "5.7.3"
        description: "Ensure security contexts are applied"
        check: |
          kubectl get pods -A -o json | jq -r '.items[] | select(.spec.securityContext == null)'
        remediation: |
          Add securityContext configurations to all pod specifications