# Terraform configuration for dev environment
# Generated by Rig CLI AI Create

terraform {
  required_version = ">= 1.0"
  
  # Backend configuration removed for easier local development
  # To use remote state, create a GCS bucket and uncomment:
  # backend "gcs" {
  #   bucket = "xometrydevops-training-terraform-state"
  #   prefix = "env/dev"
  # }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# Environment-specific modules

module "networking" {
  source = "../../modules/networking"
  
  environment = "dev"
  project_id  = var.project_id
  region      = var.region
  
  # Environment-specific network configuration
  vpc_cidr = var.vpc_cidr
  public_subnet_cidr = var.public_subnet_cidr
  private_subnet_cidr = var.private_subnet_cidr
}


module "compute" {
  source = "../../modules/compute"
  
  environment = "dev"
  project_id  = var.project_id
  region      = var.region
  
  # Instance configuration
  instance_type = var.instance_type
  instance_count = var.instance_count
  
  # Auto-scaling for production
  enable_autoscaling = false
  min_instances = 1
  max_instances = 3
  
  # Network dependencies
  vpc_id = module.networking.vpc_id
  subnet_id = module.networking.private_subnet_id
}


module "database" {
  source = "../../modules/database"
  
  environment = "dev"
  project_id  = var.project_id
  region      = var.region
  
  # Database configuration
  database_type = var.database_type
  database_version = var.database_version
  tier = "db-f1-micro"
  
  # High availability for production
  availability_type = "ZONAL"
  backup_enabled = false
  
  # Network dependencies
  vpc_id = module.networking.vpc_id
}


module "storage" {
  source = "../../modules/storage"
  
  environment = "dev"
  project_id  = var.project_id
  
  # Storage configuration
  bucket_name = "${var.project_id}-dev-storage"
  storage_class = "REGIONAL"
  
  # Lifecycle policies
  lifecycle_age = 30
  versioning_enabled = false
}


module "monitoring" {
  source = "../../modules/monitoring"
  
  environment = "dev"
  project_id  = var.project_id
  
  # Monitoring configuration
  enable_logging = true
  enable_metrics = true
  enable_alerting = false
  
  # Alert channels for production
  notification_emails = []
}
